[tool.nx]
autoActivate = true

[tool.poetry]
name = "@face-recognition-web-application/source"
version = "1.0.0"
description = ""
authors = [ ]
license = "Proprietary"
readme = "README.md"

  [tool.poetry.dependencies]
  python = ">=3.10, <3.11"
  matplotlib = "^3.9.2"
  python-socketio = {extras = ["client"], version = "^5.11.4"}
  requests = "^2.32.3"
  numpy = "^2.1.3"

    [tool.poetry.dependencies.PyPackages]
    path = "apps/Realtime-Image-Transmission"
    develop = true

[build-system]
requires = [ "poetry-core==1.1.0" ]
build-backend = "poetry.core.masonry.api"
